out_dir: result/fold_0_1
epochs: 100
bstch_size: 16
warmup_steps: 80
gradient_accumulation_steps: 10
save_steps: 10
eval_steps: 10 
learning_rate: 0.00005
save_total_limit: 2
eval_accumulation_steps: 10
dropout_prob: 0.3
